In [ ]:
# 作業目標
# 活用矩陣運算，實做線性代數
# 作業重點
# 線性代數公式應用
# 矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

# 題目:
# array1 = np.array([[10, 8], [3, 5]]) 

# 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
# 運用上列array計算特徵值、特徵向量?
# 運用上列array計算SVD?

In [2]:
import numpy as np

In [16]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
# 反矩陣
inverse_array1 = np.linalg.inv(array1)
#相乘後的結果
result_array1 = np.matmul(array1,inverse_array1)

print('array1的反矩陣為:\n{}'.format(inverse_array1))
print('-'*20)
print('array1與反矩陣相乘結果為:\n{}'.format(result_array1))
print('-'*20)
print('結果：是單位矩陣！')

array1的反矩陣為:
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
--------------------
array1與反矩陣相乘結果為:
[[1. 0.]
 [0. 1.]]
--------------------
結果：是單位矩陣！


In [18]:
#2. 運用上列array計算特徵值、特徵向量?
w,v = np.linalg.eig(array1)
print('array1的特徵值為：\n{}'.format(w))
print('-'*20)
print('array1的特徵向量為：\n{}'.format(v))

array1的特徵值為：
[13.  2.]
--------------------
array1的特徵向量為：
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [22]:
#3. 運用上列array計算SVD?
u, s , vh = np.linalg.svd(array1)
print('u:\n',u)
print('-'*20)
print('s:\n',s)
print('-'*20)
print('vh:\n',vh)

u:
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
--------------------
s:
 [13.94721714  1.86417116]
--------------------
vh:
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
